import type { Metadata } from "next";
import "./globals.css";

import { Onest } from "@/lib/fonts";
import { AppKitProvider } from "@/providers/AppkitProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Onest.variable} antialiased`} >
        <AppKitProvider>
          <Header/>
          <main className="w-full max-w-7xl mx-auto px-6">
          {children}
          </main>
          <Footer />
        </AppKitProvider>
      </body>
    </html>
  );
}
